##################################
# kind-config.yaml               #
##################################
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: observability-cluster
nodes:
- role: control-plane
  extraPortMappings:
  # Porta do Grafana (NodePort: 32300 mapeado para localhost:3000)
  - containerPort: 32300  # ALTERADO: Deve bater exatamente com o nodePort do serviço
    hostPort: 3000
    listenAddress: "0.0.0.0"
  # Porta do Prometheus (NodePort: 32090 mapeado para localhost:9090)
  - containerPort: 32090
    hostPort: 9090
    listenAddress: "0.0.0.0"
  # Porta do OpenTelemetry Collector (gRPC - NodePort: 30317 para localhost:4317)
  - containerPort: 30317
    hostPort: 4317
    listenAddress: "0.0.0.0"
  # Porta do OpenTelemetry Collector (HTTP - NodePort: 30318 para localhost:4318)
  - containerPort: 30318
    hostPort: 4318
    listenAddress: "0.0.0.0"